
install:
 - brew update && brew upgrade swiftlint
language: swift
osx_image: xcode12.5
xcode_project: PainsMedsBuddy.xcodeproj
xcode_scheme: PainsMedsBuddy
xcode_destination: platform=iOS Simulator,OS=14.5,name=iPhone 8

env:
- DESTINATION="OS=14.5,name=iPhone 8" SCHEME="PainsMedsBuddy" SDK=iphonesimulator

script:
- swiftlint
- xcodebuild clean build -project PainsMedsBuddy.xcodeproj -scheme PainsMedsBuddy -sdk iphonesimulator14.5 -destination "platform=iOS Simulator,name=iPhone 8" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
- xcodebuild test -project PainsMedsBuddy.xcodeproj -scheme PainsMedsBuddy -sdk iphonesimulator14.5 -destination "platform=iOS Simulator,name=iPhone 8" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c

