# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

screenshot_devices = [
    "iPhone 11 Pro Max",
    "iPhone 8 Plus",
    "iPad Pro (12.9-inch) (2nd generation)",
    "iPad Pro (12.9-inch) (4th generation)"
]

test_devices = [
    #"iPhone SE (2nd generation)",
    "iPhone 8",
    #"iPhone 8 Plus",
    "iPad Pro (12.9-inch) (4th generation)"
]

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    scan(
        scheme: "FastlaneScreenshots", 
        derived_data_path: 'fastlane/derived_data_path',
        build_for_testing: true,
        configuration: "Debug",
        devices: screenshot_devices,
    )

    snapshot(
        devices: screenshot_devices,
        languages: [
            "en-GB",
        ],
        scheme: "FastlaneScreenshots",
        launch_arguments: ["enable-ui-testing"],
        #output_directory: "../screenshots/PainMedsBuddy", # Causes FrameIt error
        stop_after_first_error: false, 
        number_of_retries: 0,
        output_simulator_logs: true,
        erase_simulator: false,
        clear_previous_screenshots: true,
        concurrent_simulators: true,
        test_without_building: true, # need to remove when no using ci
        derived_data_path: 'fastlane/derived_data_path'
    )
  end

  desc "Run tests on multiple devices"
  lane :tests do
    run_tests(
        scheme: "PainMedsBuddy",
        devices: test_devices,
        code_coverage: true,
        open_report: true,
        skip_build: true,
        output_style: "standard",
        output_types: "html",
        skip_detect_devices: true
    )
  end

  desc "Frame localized screenshots"
  lane :framescreens do
    frame_screenshots(
      white: true,
      path: "/Users/jm/repos/PainMedsBuddy/fastlane/screenshots"
  #    path: "../screenshots/PainMedsBuddy" # Causes FrameIt error
    )
  end

  desc "Upload localized + framed screenshots"
  lane :UploadScreens do
    deliver(
      submit_for_review: false,
      force: true,
      skip_binary_upload: true, 
      skip_app_version_update: true,
      overwrite_screenshots: true,
      skip_metadata: true,
      skip_screenshots: false
    )
  end
end
